package frc.robot.sim;

/**
 * Simulates a battery. Different batteries have different characteristics determined by the
 * implementations of this interface. The most simple implementation would be a battery that outputs
 * a constant voltage, while more a sophisticated implementation
 */
public interface BatterySim {
  /**
   * Sets the current draw generated by all running mechanisms. Call {@link #update(double)
   * update()} and then {@link #getVoltage()} to determine the output voltage of the battery after
   * setting the current draw.
   */
  void setCurrentDraw(double current);

  /**
   * Updates the simulation by stepping the simulation forward in time.
   *
   * @param timestep how much time has elapsed since the most recent update, in seconds.
   */
  void update(double timestep);

  /**
   * Gets the voltage output of the battery at the current moment in simulation. It is safe to call
   * this method multiple times in the same update tick.
   */
  double getVoltage();
}
